language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9

matrix:
  include:
    - node_js: 8
      env: HARMONY=YES
      script: ./node_modules/.bin/mocha --harmony_regexp_property -R spec test.js
    - node_js: 9
      env: HARMONY=YES
      script: ./node_modules/.bin/mocha --harmony_regexp_property -R spec test.js
